### ISSUE TITLE
47u slots

### ISSUE THREAD

**Issue by gcarrascohuertas** [Phisik/Peristaltic-Pump#2]
Thanks you for your project. It's awesome!

I have a question refered to 47u slots in PCB scheme. These two slots are for 47 microFarads capacitors?
Thanks you in advance

**Comment by gcarrascohuertas** [comment]
Also if 47 microFarads capacitor is needed. Which voltage is required ? 47 microFarads -  16V ?

**Comment by Phisik** [comment]
Hello! Yes, you are right. It's better to solder a couple of 47-100u caps on the board. However it mostly will do ok wihout them. I would suggest to use the capacitors with max voltage 2 time higher than VIN, e.g. if VIN=12V then take 25V caps.
